version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./Docker/app-mysql/Dockerfile
#    restart: always
    volumes:
      - ./:/app
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_started

#  fake_data:
#    build:
#      context: ./Docker/app-data
#    volumes:
#      - ./.fake-data/:/app

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 0
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=${DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-config:/etc/mysql

  mongo:
    image: mongo:latest
    ports:
      - "29017:29017"
#    healthcheck:
#      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
#      interval: 5s
#      timeout: 5s
#      retries: 0
#      start_period: 5s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb-data:/data/db

volumes:
  mysql-data:
  mysql-config:
  mongodb-data:
  .fake-data:
